import Link from "next/link";
import Image from "next/image";
import { ArrowDown, ArrowRight, MapPin } from "lucide-react";
import { HeaderNavigation } from "@/components/organisms/HeaderNavigation";
import { HeritageGallery } from "@/components/organisms/HeritageGallery";
import { basePath } from "@/lib/site-config";

export default function SitesPage() {
  return <>
    <HeaderNavigation overlay />
    <main>
      <section className="relative isolate min-h-[620px] overflow-hidden bg-sea-900 text-sand-100 sm:min-h-[710px]">
        <Image src={`${basePath}/heritage/hundred-islands.jpg`} alt="Aerial view of Hundred Islands National Park" fill priority sizes="100vw" className="-z-20 object-cover object-center" />
        <div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(4,28,31,.93)_0%,rgba(7,45,48,.68)_50%,rgba(5,38,43,.16)_100%)]" /><div className="pointer-events-none absolute inset-x-0 bottom-0 h-40 text-white/35"><svg className="h-full w-full" viewBox="0 0 1200 160" preserveAspectRatio="none" fill="none"><path d="M0 70 Q170 10 390 65 T780 60 T1200 45" stroke="currentColor" strokeWidth="1.5" /><path d="M0 105 Q200 50 420 105 T800 98 T1200 78" stroke="currentColor" strokeWidth="1" /></svg></div>
        <div className="relative mx-auto flex min-h-[620px] max-w-6xl items-center px-5 pb-20 pt-28 sm:min-h-[710px] sm:px-6 sm:pt-32"><div className="max-w-3xl animate-[fadeUp_.8s_ease-out_both]"><p className="font-mono text-[11px] font-medium uppercase tracking-[.2em] text-[#f3b75c]">Pangasinan Provincial Tourism Office</p><div className="mt-6 inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3.5 py-2 text-xs text-white/90 backdrop-blur-sm"><MapPin className="size-3.5 text-[#f3b75c]" /> Pangasinan, Philippines</div><h1 className="mt-6 font-display text-[clamp(3.25rem,8vw,6.3rem)] font-semibold leading-[.95] tracking-[-.045em]">Heritage worth exploring, <em className="font-medium text-[#f4bd68]">image by image.</em></h1><p className="mt-6 max-w-xl text-base leading-relaxed text-white/85 sm:text-lg">Browse Pangasinan’s natural wonders, historic landmarks, and the stories that continue to shape the province.</p><a href="#heritage-gallery" className="mt-8 inline-flex items-center gap-2 rounded-full bg-coral px-6 py-3.5 text-sm font-semibold text-white shadow-xl shadow-black/25 transition hover:-translate-y-0.5 hover:bg-coral-600">Browse the gallery <ArrowRight className="size-4" /></a></div></div>
        <a href="#heritage-gallery" aria-label="Scroll to heritage gallery" className="absolute bottom-8 left-1/2 flex -translate-x-1/2 flex-col items-center gap-2 text-[10px] uppercase tracking-[.18em] text-white/75"><span>Explore all sites</span><ArrowDown className="size-4 animate-bounce" /></a><svg className="absolute inset-x-0 bottom-0 block h-10 w-full text-sand-100 sm:h-16" viewBox="0 0 1440 80" preserveAspectRatio="none" aria-hidden="true"><path d="M0 45 C240 100 410 5 700 48 C990 92 1190 35 1440 22 V80 H0Z" fill="currentColor" /></svg>
      </section>
      <section id="heritage-gallery" className="relative overflow-hidden bg-sand-100 py-20 sm:py-28"><div className="pointer-events-none absolute -left-12 top-28 hidden h-72 w-36 rounded-full border border-moss/15 md:block" /><div className="pointer-events-none absolute -right-12 top-20 hidden h-80 w-40 rounded-full border border-moss/15 md:block" /><div className="relative mx-auto max-w-6xl px-5 sm:px-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div className="max-w-2xl"><p className="font-mono text-[11px] uppercase tracking-[.2em] text-coral">Discover Pangasinan’s treasures</p><h2 className="mt-3 font-display text-4xl font-semibold leading-tight text-sea-900 sm:text-5xl">The Heritage Gallery</h2><p className="mt-4 text-base leading-relaxed text-ink/70 sm:text-lg">Tap into every destination, linger on the view, and browse the stories of Pangasinan at your own pace.</p></div><p className="max-w-xs text-sm leading-relaxed text-ink/60">Select any image for a full-screen viewing experience.</p></div><HeritageGallery /></div></section>
    </main>
    <footer className="bg-sea-900 py-10 text-sand-100/70"><div className="mx-auto flex max-w-6xl flex-col gap-3 px-5 text-sm sm:flex-row sm:items-center sm:justify-between sm:px-6"><p>Pangasinan Heritage Digital Showcase — Provincial Tourism Office.</p><Link href="/plan-a-visit" className="font-semibold text-[#f3b75c] hover:text-white">Plan your visit →</Link></div></footer>
  </>;
}
