import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowRight, Church, Compass, Landmark, MapPin, Palmtree, Sparkles, Waves } from "lucide-react";
import { HeaderNavigation } from "@/components/organisms/HeaderNavigation";
import { DestinationHighlights } from "@/components/organisms/DestinationHighlights";
import { basePath } from "@/lib/site-config";


const reasons = [
  { icon: Landmark, title: "Rich Heritage", text: "Stories of faith, trade, and community live on in every town." },
  { icon: Waves, title: "Beautiful Beaches", text: "Find quiet shores, island coves, and vast coastal horizons." },
  { icon: Church, title: "Historic Landmarks", text: "Step into chapels, homes, and monuments shaped by time." },
  { icon: Palmtree, title: "Natural Wonders", text: "From hot springs to limestone isles, nature is close at hand." },
];


function SectionIntro({ eyebrow, title, text }: { eyebrow: string; title: string; text?: string }) {
  return <div className="max-w-2xl"><p className="font-mono text-[11px] font-medium uppercase tracking-[0.2em] text-coral">{eyebrow}</p><h2 className="mt-3 font-display text-3xl font-semibold leading-tight text-sea-900 sm:text-4xl lg:text-5xl">{title}</h2>{text && <p className="mt-4 text-base leading-relaxed text-ink/70 sm:text-lg">{text}</p>}</div>;
}

export default function Home() {
  return <div id="top" className="min-h-screen overflow-hidden bg-sand-100">
    <section className="relative isolate min-h-[720px] overflow-hidden bg-sea-900 text-sand-100 sm:min-h-[780px]">
      <Image src={`${basePath}/heritage/hundred-islands.jpg`} alt="Aerial view of Hundred Islands National Park" fill priority sizes="100vw" className="-z-20 object-cover object-center" />
      <div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(4,28,31,.94)_0%,rgba(7,45,48,.72)_46%,rgba(5,38,43,.18)_100%)]" /><div className="absolute inset-x-0 bottom-0 h-44 bg-gradient-to-t from-sea-900/70 to-transparent" />
      <HeaderNavigation overlay />
      <div className="mx-auto flex min-h-[720px] max-w-6xl items-center px-5 pb-24 pt-28 sm:min-h-[780px] sm:px-6 sm:pt-32"><div className="max-w-3xl animate-[fadeUp_.8s_ease-out_both]">
        <div className="inline-flex items-center gap-2 rounded-full border border-white/25 bg-white/10 px-3.5 py-2 text-xs font-medium tracking-wide backdrop-blur-sm"><MapPin className="size-3.5 text-[#f3b75c]" /> Pangasinan, Philippines</div>
        <p className="mt-7 font-mono text-xs uppercase tracking-[0.19em] text-[#f3b75c]">Pangasinan Provincial Tourism Office</p><h1 className="mt-4 font-display text-[clamp(3rem,7vw,5.6rem)] font-semibold leading-[.98] tracking-[-0.045em]">Discover Pangasinan&apos;s heritage, <em className="font-display font-medium text-[#f4bd68]">coast to hot spring.</em></h1>
        <p className="mt-6 max-w-xl text-base leading-relaxed text-sand-100/90 sm:text-lg">Follow the tide to storied shores, centuries-old landmarks, and quiet places that reveal the soul of Pangasinan.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/sites" className="inline-flex items-center justify-center gap-2 rounded-full bg-coral px-6 py-3.5 text-sm font-semibold text-white shadow-xl shadow-black/20 transition hover:-translate-y-0.5 hover:bg-coral-600">Explore Heritage Sites <ArrowRight className="size-4" /></Link><Link href="/plan-a-visit" className="inline-flex items-center justify-center gap-2 rounded-full border border-white/35 bg-white/10 px-6 py-3.5 text-sm font-semibold text-white backdrop-blur-sm transition hover:-translate-y-0.5 hover:bg-white hover:text-sea-900">Plan Your Visit</Link></div>
      </div></div><a href="#heritage" aria-label="Scroll to heritage sites" className="absolute bottom-8 left-1/2 flex -translate-x-1/2 flex-col items-center gap-2 text-[10px] font-medium uppercase tracking-[.18em] text-white/80 transition hover:text-white"><span>Scroll to explore</span><ArrowDown className="size-4 animate-bounce" /></a>
    </section>
    <main>      <section className="bg-[#e7efe5] py-20 sm:py-24"><div className="mx-auto max-w-6xl px-5 sm:px-6"><SectionIntro eyebrow="Why Pangasinan" title="Made for meaningful wandering" text="A destination where the day can move from a heritage trail to a sea horizon, without losing its warmth." /><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{reasons.map(({ icon: Icon, title, text }) => <div key={title} className="rounded-2xl border border-moss/10 bg-white/70 p-6 transition hover:-translate-y-1 hover:bg-white"><span className="grid size-11 place-items-center rounded-full bg-moss text-white"><Icon className="size-5" /></span><h3 className="mt-5 font-display text-xl font-semibold text-sea-900">{title}</h3><p className="mt-2 text-sm leading-relaxed text-ink/65">{text}</p></div>)}</div></div></section>
      <section className="bg-sea-900 px-5 py-16 sm:px-6 sm:py-24"><div className="mx-auto grid max-w-6xl overflow-hidden rounded-3xl bg-sea-700 lg:grid-cols-2"><div className="relative min-h-[300px] lg:min-h-full"><Image src={`${basePath}/heritage/getting-around.jpg`} alt="Coastal Pangasinan scenery" fill sizes="(min-width: 1024px) 50vw, 100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-sea-900/45 to-transparent" /></div><div className="flex flex-col justify-center p-8 text-sand-100 sm:p-12 lg:p-16"><p className="font-mono text-[11px] uppercase tracking-[.2em] text-[#f3b75c]">Travel with ease</p><h2 className="mt-4 font-display text-3xl font-semibold leading-tight sm:text-4xl">Plan Your Perfect Pangasinan Adventure</h2><p className="mt-5 max-w-lg leading-relaxed text-sand-100/75">Everything you need to know for a smooth, safe, and memorable trip across Pangasinan.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/plan-a-visit" className="rounded-full bg-[#f3b75c] px-5 py-3 text-sm font-semibold text-sea-900 transition hover:bg-white">Plan Your Visit</Link><Link href="/plan-a-visit" className="rounded-full border border-white/30 px-5 py-3 text-sm font-semibold text-white transition hover:bg-white/10">View Travel Guide</Link></div></div></div></section>
      <section className="bg-sand-100 py-20 sm:py-28"><div className="mx-auto max-w-6xl px-5 sm:px-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><SectionIntro eyebrow="More to discover" title="Destination Highlights" /><p className="max-w-sm text-sm leading-relaxed text-ink/65">Choose your own pace—from a lazy coast day to a trail through the province's deepest stories.</p></div><DestinationHighlights /></div></section>
      <section className="bg-[#f3eee2] py-20 sm:py-28"><div className="mx-auto grid max-w-6xl items-center gap-10 px-5 sm:px-6 lg:grid-cols-2 lg:gap-16"><div className="relative aspect-[5/4] overflow-hidden rounded-3xl"><Image src={`${basePath}/heritage/urduwa.jpg`} alt="Historic Urduja House in Lingayen" fill sizes="(min-width: 1024px) 50vw, 100vw" className="object-cover" /><div className="absolute bottom-5 left-5 flex items-center gap-2 rounded-full bg-sea-900/85 px-3 py-2 text-xs font-medium text-white backdrop-blur"><Sparkles className="size-3.5 text-[#f3b75c]" /> Living heritage</div></div><div><SectionIntro eyebrow="The Pangasinan story" title="Where History Meets the Coast" text="Pangasinan has always been shaped by the water: a place of trade, faith, harvest, and hospitality. Its churches, homes, coastlines, and everyday traditions hold a heritage that is not only preserved—it is lived." /><Link href="/about" className="mt-7 inline-flex items-center gap-2 rounded-full bg-sea-900 px-5 py-3 text-sm font-semibold text-white transition hover:bg-moss">Discover Our Heritage <ArrowRight className="size-4" /></Link></div></div></section>
      <section className="relative isolate overflow-hidden bg-moss py-20 text-center text-white sm:py-28"><div className="absolute inset-0 -z-10 opacity-20 [background-image:radial-gradient(#f3b75c_1px,transparent_1px)] [background-size:22px_22px]" /><Compass className="absolute -right-10 top-4 size-48 rotate-12 text-white/10 sm:right-12" /><div className="mx-auto max-w-2xl px-5 sm:px-6"><p className="font-mono text-[11px] uppercase tracking-[.2em] text-[#f3d18b]">Begin your journey</p><h2 className="mt-4 font-display text-4xl font-semibold leading-tight sm:text-5xl">Your Pangasinan Story Starts Here.</h2><p className="mt-5 text-lg leading-relaxed text-white/80">Discover places, stories, and traditions that make Pangasinan unforgettable.</p><Link href="/sites" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#f3b75c] px-6 py-3.5 text-sm font-semibold text-sea-900 transition hover:-translate-y-0.5 hover:bg-white">Start Exploring <ArrowRight className="size-4" /></Link></div></section>
    </main>
    <footer className="bg-sea-900 text-sand-100"><div className="mx-auto grid max-w-6xl gap-10 px-5 py-14 sm:px-6 md:grid-cols-[1.5fr_1fr_1fr]"><div><Link href="/" className="flex items-center gap-3 font-display text-xl font-semibold"><Image src={`${basePath}/heritage/logo.jpg`} alt="Pangasinan Province logo" width={48} height={48} className="size-12 object-contain" />Pangasinan Heritage</Link><p className="mt-5 max-w-sm text-sm leading-relaxed text-sand-100/65">A digital showcase of the places, memories, and traditions that make Pangasinan remarkable.</p></div><div><h2 className="font-mono text-[11px] uppercase tracking-[.18em] text-[#f3b75c]">Explore</h2><ul className="mt-4 space-y-3 text-sm text-sand-100/75"><li><Link href="/sites" className="hover:text-white">Heritage Sites</Link></li><li><Link href="/plan-a-visit" className="hover:text-white">Plan a Visit</Link></li><li><Link href="/about" className="hover:text-white">About Pangasinan</Link></li></ul></div><div><h2 className="font-mono text-[11px] uppercase tracking-[.18em] text-[#f3b75c]">Tourism information</h2><p className="mt-4 text-sm leading-relaxed text-sand-100/65">Pangasinan Provincial Tourism Office<br />Lingayen, Pangasinan, Philippines</p><a href="#top" className="mt-4 inline-flex text-sm font-semibold text-[#f3b75c] hover:text-white">Back to top ↑</a></div></div><div className="border-t border-white/10"><p className="mx-auto max-w-6xl px-5 py-5 text-xs text-sand-100/50 sm:px-6">© {new Date().getFullYear()} Pangasinan Heritage Digital Showcase. All rights reserved.</p></div></footer>
  </div>;
}
