"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import Image from "next/image";
import { ArrowRight, MapPin, Search, X } from "lucide-react";
import { heritageSites, type Destination } from "@/lib/heritage-sites";
import { DestinationDetailModal } from "@/components/organisms/DestinationDetailModal";

function scoreDestination(destination: Destination, query: string) {
  const name = destination.name.toLowerCase(); const municipality = destination.municipality.toLowerCase(); const keywords = destination.keywords.join(" ").toLowerCase(); const description = destination.description.toLowerCase();
  if (name === query) return 0; if (name.startsWith(query)) return 1; if (name.includes(query)) return 2; if (municipality.includes(query)) return 3; if (keywords.includes(query)) return 4; if (description.includes(query)) return 5; return 99;
}

export function SearchForm({ onSearch, className = "", inputId = "heritage-search" }: { onSearch?: (query: string) => void; className?: string; inputId?: string; }) {
  const [query, setQuery] = useState(""); const [isOpen, setIsOpen] = useState(false); const [selected, setSelected] = useState<Destination | null>(null); const containerRef = useRef<HTMLDivElement>(null);
  const normalizedQuery = query.trim().toLowerCase();
  const results = useMemo(() => !normalizedQuery ? [] : heritageSites.filter((site) => scoreDestination(site, normalizedQuery) < 99).sort((a, b) => scoreDestination(a, normalizedQuery) - scoreDestination(b, normalizedQuery)), [normalizedQuery]);
  useEffect(() => { const onPointerDown = (event: MouseEvent) => { if (containerRef.current && !containerRef.current.contains(event.target as Node)) setIsOpen(false); }; const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape") setIsOpen(false); }; document.addEventListener("mousedown", onPointerDown); document.addEventListener("keydown", onKeyDown); return () => { document.removeEventListener("mousedown", onPointerDown); document.removeEventListener("keydown", onKeyDown); }; }, []);
  function handleSubmit(event: FormEvent) { event.preventDefault(); onSearch?.(normalizedQuery); if (results[0]) { setSelected(results[0]); setIsOpen(false); } }
  function selectDestination(destination: Destination) { setSelected(destination); setIsOpen(false); setQuery(""); }
  return <div ref={containerRef} className={`relative w-full ${className}`}><form role="search" onSubmit={handleSubmit}><label htmlFor={inputId} className="sr-only">Search destinations and heritage sites</label><div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 size-[18px] -translate-y-1/2 text-ink/50" /><input id={inputId} type="search" value={query} onFocus={() => query.trim() && setIsOpen(true)} onChange={(event) => { setQuery(event.target.value); setIsOpen(Boolean(event.target.value.trim())); }} placeholder="Search destinations..." autoComplete="off" className="w-full rounded-full border border-ink/15 bg-white py-2.5 pl-10 pr-10 text-sm text-ink placeholder:text-ink/40 shadow-sm focus:outline-none focus-visible:outline-3 focus-visible:outline-coral" />{query && <button type="button" onClick={() => { setQuery(""); setIsOpen(false); }} className="absolute right-2 top-1/2 grid size-7 -translate-y-1/2 place-items-center rounded-full text-ink/55 transition hover:bg-sea-900/10 hover:text-sea-900" aria-label="Clear search"><X className="size-4" /></button>}</div></form>{isOpen && normalizedQuery && <div className="absolute left-0 right-0 top-[calc(100%+0.5rem)] z-[90] max-h-[min(60vh,430px)] overflow-y-auto rounded-2xl border border-sea-900/10 bg-sand-100 p-2 shadow-2xl"><p className="px-3 pb-2 pt-1 font-mono text-[10px] font-medium uppercase tracking-[.16em] text-moss-700">{results.length ? `${results.length} search result${results.length === 1 ? "" : "s"}` : "Search results"}</p>{results.length ? results.map((destination) => <button type="button" key={destination.slug} onClick={() => selectDestination(destination)} className="flex w-full gap-3 rounded-xl p-2 text-left transition hover:bg-white"><div className="relative size-14 shrink-0 overflow-hidden rounded-lg"><Image src={destination.image} alt="" fill sizes="56px" className="object-cover" /></div><span className="min-w-0 flex-1"><span className="block truncate font-display text-base font-semibold text-sea-900">{destination.name}</span><span className="mt-0.5 flex items-center gap-1 text-xs text-ink/60"><MapPin className="size-3" /> {destination.municipality}, Pangasinan</span><span className="mt-1 inline-flex items-center gap-1 text-xs font-semibold text-coral">View <ArrowRight className="size-3" /></span></span></button>) : <div className="px-3 py-5"><p className="font-display text-lg font-semibold text-sea-900">No destinations found.</p><p className="mt-1 text-sm leading-relaxed text-ink/65">Try searching for another place, municipality, or attraction.</p></div>}</div>}{selected && <DestinationDetailModal destination={selected} onClose={() => setSelected(null)} />}</div>;
}
