import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowRight, Camera, MapPin, Sun, Ticket } from "lucide-react";
import { HeaderNavigation } from "@/components/organisms/HeaderNavigation";
import { TipCard } from "@/components/organisms/TipCard";

const tips = [
  { title: "Best time to visit", body: "November to May offers the driest weather for island-hopping and outdoor sightseeing across Pangasinan.", image: "/heritage/best-time.jpg", icon: "sun" },
  { title: "Getting around", body: "Alaminos, Bolinao, and Balungao are best reached by private vehicle or provincial bus routes from the Alaminos terminal.", image: "/heritage/getting-around.jpg", icon: "map" },
  { title: "What to bring", body: "Pack sun protection and swimwear, comfortable shoes for heritage walks, and a light jacket for cooler mornings.", image: "/heritage/what-to-bring.jpg", icon: "backpack" },
  { title: "Local etiquette", body: "Ask permission before photographing residents, support local guides and vendors, and respect conservation guidelines.", image: "/heritage/etiquette.jpg", icon: "heart" },
];

const essentials = [
  { icon: MapPin, title: "Getting There", text: "Pangasinan is reachable by provincial bus or private car from Metro Manila and nearby regions." },
  { icon: Sun, title: "Weather", text: "For bright beach days, plan between November and May and always check local conditions." },
  { icon: Ticket, title: "What to Pack", text: "Bring water, reef-safe sun protection, cash for local stalls, and comfortable footwear." },
  { icon: Camera, title: "Explore Nearby", text: "Leave time for local markets, coastal viewpoints, and heritage stops beyond your itinerary." },
];

export default function PlanAVisitPage() {
  return <>
    <HeaderNavigation overlay />
    <main>
      <section className="relative isolate min-h-[620px] overflow-hidden bg-sea-900 text-white sm:min-h-[710px]">
        <Image src="/heritage/bolinao-lighthouse.jpg" alt="Cape Bolinao Lighthouse overlooking the coast" fill priority sizes="100vw" className="-z-20 object-cover object-center" />
        <div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(5,29,30,.93)_0%,rgba(5,43,45,.67)_50%,rgba(5,37,42,.18)_100%)]" /><div className="pointer-events-none absolute inset-x-0 bottom-0 h-40 text-white/35"><svg className="h-full w-full" viewBox="0 0 1200 160" preserveAspectRatio="none" fill="none"><path d="M0 70 Q170 10 390 65 T780 60 T1200 45" stroke="currentColor" strokeWidth="1.5" /><path d="M0 105 Q200 50 420 105 T800 98 T1200 78" stroke="currentColor" strokeWidth="1" /></svg></div>
        <div className="relative mx-auto flex min-h-[620px] max-w-6xl items-center px-5 pb-20 pt-28 sm:min-h-[710px] sm:px-6 sm:pt-32"><div className="max-w-3xl animate-[fadeUp_.8s_ease-out_both]"><p className="font-mono text-[11px] font-medium uppercase tracking-[.2em] text-[#f3b75c]">Plan your Pangasinan journey</p><div className="mt-6 inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3.5 py-2 text-xs text-white/90 backdrop-blur-sm"><MapPin className="size-3.5 text-[#f3b75c]" /> Pangasinan, Philippines</div><h1 className="mt-6 font-display text-[clamp(3.25rem,8vw,6.3rem)] font-semibold leading-[.95] tracking-[-.045em]">Plan a trip to <em className="font-medium text-[#f4bd68]">remember.</em></h1><p className="mt-6 max-w-xl text-base leading-relaxed text-white/85 sm:text-lg">Everything you need to know for a smooth, safe, and memorable trip across Pangasinan.</p><a href="#travel-guide" className="mt-8 inline-flex items-center gap-2 rounded-full bg-coral px-6 py-3.5 text-sm font-semibold text-white shadow-xl shadow-black/25 transition hover:-translate-y-0.5 hover:bg-coral-600">Explore Travel Guide <ArrowRight className="size-4" /></a></div></div>
        <a href="#travel-guide" aria-label="Scroll to travel guide" className="absolute bottom-8 left-1/2 flex -translate-x-1/2 flex-col items-center gap-2 text-[10px] uppercase tracking-[.18em] text-white/75"><span>Start planning</span><ArrowDown className="size-4 animate-bounce" /></a><svg className="absolute inset-x-0 bottom-0 block h-10 w-full text-sand-100 sm:h-16" viewBox="0 0 1440 80" preserveAspectRatio="none" aria-hidden="true"><path d="M0 45 C240 100 410 5 700 48 C990 92 1190 35 1440 22 V80 H0Z" fill="currentColor" /></svg>
      </section>
      <section id="travel-guide" className="bg-sand-100 py-20 sm:py-28"><div className="mx-auto max-w-6xl px-5 sm:px-6"><div className="max-w-2xl"><p className="font-mono text-[11px] uppercase tracking-[.2em] text-coral">Plan a visit</p><h2 className="mt-3 font-display text-4xl font-semibold leading-tight text-sea-900 sm:text-5xl">Travel guide &amp; tips</h2><p className="mt-4 text-base leading-relaxed text-ink/70 sm:text-lg">Helpful information to help you plan your trip and make the most of your visit.</p></div><ul className="mt-11 grid grid-cols-1 gap-5 md:grid-cols-2 md:gap-6">{tips.map((tip, index) => <TipCard key={tip.title} tip={tip} index={index} />)}</ul></div></section>
      <section className="bg-[#e7efe5] py-20 sm:py-24"><div className="mx-auto max-w-6xl px-5 sm:px-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono text-[11px] uppercase tracking-[.2em] text-coral">Travel essentials</p><h2 className="mt-3 font-display text-4xl font-semibold leading-tight text-sea-900 sm:text-5xl">Make your Pangasinan adventure easier.</h2></div><p className="max-w-sm text-sm leading-relaxed text-ink/65">A little preparation makes room for the experiences you will remember most.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{essentials.map(({ icon: Icon, title, text }) => <div key={title} className="rounded-2xl border border-moss/10 bg-white/75 p-6 transition hover:-translate-y-1 hover:bg-white"><span className="grid size-11 place-items-center rounded-full bg-moss text-white"><Icon className="size-5" /></span><h3 className="mt-5 font-display text-xl font-semibold text-sea-900">{title}</h3><p className="mt-2 text-sm leading-relaxed text-ink/65">{text}</p></div>)}</div></div></section>
      <section className="bg-sea-900 px-5 py-16 sm:px-6 sm:py-24"><div className="relative mx-auto max-w-6xl overflow-hidden rounded-3xl"><Image src="/heritage/hundred-islands.jpg" alt="Hundred Islands National Park" fill sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(5,42,43,.94),rgba(5,42,43,.60),rgba(5,42,43,.28))]" /><div className="relative min-h-[380px] px-8 py-14 text-white sm:flex sm:min-h-[430px] sm:items-center sm:px-14"><div className="max-w-xl"><p className="font-mono text-[11px] uppercase tracking-[.2em] text-[#f3b75c]">Your next chapter</p><h2 className="mt-4 font-display text-4xl font-semibold leading-tight sm:text-5xl">Ready to discover Pangasinan?</h2><p className="mt-5 text-base leading-relaxed text-white/80 sm:text-lg">From historic landmarks to island adventures, start planning your journey through the province.</p><Link href="/sites" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#f3b75c] px-6 py-3.5 text-sm font-semibold text-sea-900 transition hover:-translate-y-0.5 hover:bg-white">Explore Heritage Sites <ArrowRight className="size-4" /></Link></div></div></div></section>
    </main>
    <footer className="bg-sea-900 py-10 text-sand-100/70"><div className="mx-auto flex max-w-6xl flex-col gap-3 px-5 text-sm sm:flex-row sm:items-center sm:justify-between sm:px-6"><p>Pangasinan Heritage Digital Showcase — Provincial Tourism Office.</p><Link href="/about" className="font-semibold text-[#f3b75c] hover:text-white">Learn about Pangasinan →</Link></div></footer>
  </>;
}

